/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_prvak_memoryeater_NativeBite */

#ifndef _Included_net_prvak_memoryeater_NativeBite
#define _Included_net_prvak_memoryeater_NativeBite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_prvak_memoryeater_NativeBite
 * Method:    allocate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_prvak_memoryeater_NativeBite_allocate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
